NO_TYPE = 'NO_TYPE'
OPERATOR = 'OPERATOR'
INTEGER = 'INTEGER'
FLOAT = 'FLOAT'
STRING = 'STRING'
TUPLE = 'TUPLE'
LIST = 'LIST'
VARIABLE = 'VARIABLE'
FCALL = 'FCALL'

PARENTHESIS = 'PARENTHESIS'        # ()
BRACES = 'BRACES'                  # {}
SQUARE_BRACES = 'SQUARE_BRACES'    # []
NEWLINE = 'NEWLINE'
SEMICOLON = 'SEMICOLON'

FUNC_ASSIGN = 'FUNC_ASSIGN'
VAR_ASSIGN = 'VAR_ASSIGN'
FOR_LOOP = 'FOR_LOOP'
IF_STMNT = 'IF_STMNT'
ELIF_STMNT = 'ELIF_STMNT'
ELSE_STMNT = 'ELSE_STMNT'

KEYWORD = 'KEYWORD'
FUNC_KEYWORD = 'FUNC_KEYWORD'
CLASS_KEYWORD = 'CLASS_KEYWORD'
RETURN_KEYWORD = 'RETURN_KEYWORD'
CONTINUE_KEYWORD = 'CONTINUE_KEYWORD'
BREAK_KEYWORD = 'BREAK_KEYWORD'
FOR_KEYWORD = 'FOR_KEYWORD'
IF_KEYWORD = 'IF_KEYWORD'
ELIF_KEYWORD = 'ELIF_KEYWORD'
ELSE_KEYWORD = 'ELSE_KEYWORD'

ANY = 'ANY'                          # constant used for semantic

pytypes2lotus = {
    int: INTEGER,
    float: FLOAT,
    str: STRING,
}

keywords = {
    'func': FUNC_KEYWORD,
    'class': CLASS_KEYWORD,
    'return': RETURN_KEYWORD,
    'continue': CONTINUE_KEYWORD,
    'break': BREAK_KEYWORD,
    'for': FOR_KEYWORD,
    'if': IF_KEYWORD,
    'elif': ELIF_KEYWORD,
    'else': ELSE_KEYWORD,
}
